incorporate thread control in config tool

diff --git a/HeterogeneousCore/SonicTriton/scripts/cmsTriton b/HeterogeneousCore/SonicTriton/scripts/cmsTriton
--- a/HeterogeneousCore/SonicTriton/scripts/cmsTriton
+++ b/HeterogeneousCore/SonicTriton/scripts/cmsTriton
@@ -34,7 +34,7 @@ get_sandbox(){
 
 usage() {
 	ECHO="echo -e"
-	$ECHO "cmsTriton [options] [start|stop|check|checksum]"
+	$ECHO "cmsTriton [options] [start|stop|check]"
 	$ECHO
 	$ECHO "Options:"
 	$ECHO "-c          \t don't cleanup temporary dir (for debugging)"
@@ -61,7 +61,6 @@ usage() {
 	$ECHO "start       \t start server"
 	$ECHO "stop        \t stop server"
 	$ECHO "check       \t check if server can run on this system"
-	$ECHO "checksum    \t update model checksums"
 	exit $1
 }
 
@@ -117,7 +116,7 @@ done
 shift $(($OPTIND - 1))
 OP=$1
 
-if [ "$OP" != start ] && [ "$OP" != stop ] && [ "$OP" != check ] && [ "$OP" != checksum ]; then
+if [ "$OP" != start ] && [ "$OP" != stop ] && [ "$OP" != check ]; then
 	usage 1
 fi
 
@@ -339,57 +338,6 @@ wait_server(){
 	echo "server is ready!"
 }
 
-edit_model(){
-	MODELNAME=$1
-	NUMINSTANCES=$2
-	
-	cp -r $MODELNAME $TMPDIR/$LOCALMODELREPO/
-	COPY_EXIT=$?
-	if [ "$COPY_EXIT" -ne 0 ]; then
-		echo "Could not copy $MODELNAME into $TMPDIR/$LOCALMODELREPO/"
-		exit "$COPY_EXIT"
-	fi
-	IFS='/' read -ra ADDR <<< "$MODELNAME"
-	CONFIG=$TMPDIR/$LOCALMODELREPO/${ADDR[-1]}/config.pbtxt
-
-	PLATFORM=$(grep -m 1 "^platform:" "$CONFIG")
-
-	if [[ $PLATFORM == *"ensemble"* ]]; then
-		#recurse over submodels of ensemble model
-		MODELLOC=$(echo ""${ADDR[@]:0:${#ADDR[@]}-1} | sed "s/ /\//g")
-		SUBNAME=$(grep "model_name:" "$CONFIG" | sed 's/model_name://; s/"//g')
-		for SUBMODEL in ${SUBNAME}; do
-			SUBMODEL=${MODELLOC}/${SUBMODEL}
-			edit_model $SUBMODEL "$INSTANCES"
-		done
-	else
-		#This is not an ensemble model, so we should edit the config file
-		cat <<EOF >> $CONFIG
-instance_group [
-  {
-    count: $NUMINSTANCES
-    kind: KIND_CPU
-  }
-]
-
-EOF
-		if [[ $PLATFORM == *"onnx"* ]]; then
-			cat <<EOF >> $CONFIG
-parameters { key: "intra_op_thread_count" value: { string_value: "1" } }
-parameters { key: "inter_op_thread_count" value: { string_value: "1" } }
-EOF
-		elif [[ $PLATFORM == *"tensorflow"* ]]; then
-			cat <<EOF >> $CONFIG
-parameters { key: "TF_NUM_INTRA_THREADS" value: { string_value: "1" } }
-parameters { key: "TF_NUM_INTER_THREADS" value: { string_value: "1" } }
-parameters { key: "TF_USE_PER_SESSION_THREADS" value: { string_value: "1" } }
-EOF
-		else
-			echo "Warning: thread (instance) control not implemented for $PLATFORM"
-		fi
-	fi
-}
-
 list_models(){
 	# make list of model repositories
 	LOCALMODELREPO="local_model_repo"
@@ -412,7 +360,12 @@ list_models(){
 			MODEL="$(dirname "$MODEL")"
 		fi
 		if [ "$INSTANCES" -gt 0 ]; then
-			edit_model $MODEL "$INSTANCES"
+			$DRYRUN cmsTritonConfigTool threadcontrol -c ${MODEL}/config.pbtxt --copy $TMPDIR/$LOCALMODELREPO --nThreads $INSTANCES
+			TOOL_EXIT=$?
+			if [ "$TOOL_EXIT" -ne 0 ]; then
+				echo "Could not apply threadcontrol to $MODEL"
+				exit "$TOOL_EXIT"
+			fi
 		else
 			REPOS+=("$(dirname "$MODEL")")
 		fi
@@ -567,57 +520,6 @@ check_drivers(){
 	else
 		return 1
 	fi
-}
-
-model_checksums(){
-	# get all models from repo dirs
-	for REPO in ${REPOS[@]}; do
-		for MODEL in $REPO/*/; do
-			MODELS+=("$MODEL")
-		done
-	done
-	CURDIR=$PWD
-	for MODEL in ${MODELS[@]}; do
-		# always go back to current directory first in case of relative paths
-		cd $CURDIR
-		cd $MODEL
-		CONFIG=config.pbtxt
-		if [ ! -w $CONFIG ]; then
-			echo "Config file for model $MODEL not writable"
-			continue
-		fi
-		if ! grep -q model_repository_agents ${CONFIG}; then
-			cat << EOF >> ${CONFIG}
-model_repository_agents {
-  agents [
-    { name: "checksum", parameters [
-      ]
-    }
-  ]
-}
-EOF
-		fi
-		for FILE in */*; do
-			SEARCH='key: "'$FILE'"'
-			CHECKSUM_NEW=$(md5sum $FILE | cut -d' ' -f1)
-			LINE_NEW='      { '"$SEARCH"', value: "'$CHECKSUM_NEW'" },'
-			LINE=$(grep -s "$SEARCH" ${CONFIG})
-			FOUND=$?
-			if [ $FOUND -eq 0 ]; then
-				# recheck the checksum
-				CHECKSUM_OLD=$(echo $LINE | grep -E -o 'value: "(.*)"' | cut -d' ' -f2 | tr -d '"')
-				if [[ "$CHECKSUM_OLD" != "$CHECKSUM_NEW" ]]; then
-					echo "Updating checksum for $FILE"
-					sed -i '\|'"$SEARCH"'|c\'"$LINE_NEW" $CONFIG
-				fi
-			else
-				# create checksum
-				echo "Creating checksum for $FILE"
-				SECTION='name: "checksum"'
-				sed -i '\|'"$SECTION"'|a\'"$LINE_NEW" $CONFIG
-			fi
-		done
-	done
 }
 
 if [ -n "$USEDOCKER" ]; then
