use tmp dir

diff --git a/HeterogeneousCore/SonicTriton/scripts/edmTriton b/HeterogeneousCore/SonicTriton/scripts/edmTriton
--- a/HeterogeneousCore/SonicTriton/scripts/edmTriton
+++ b/HeterogeneousCore/SonicTriton/scripts/edmTriton
@@ -15,7 +15,7 @@ usage() {
 	$ECHO "Options:"
 	$ECHO "-d        \t use Docker instead of Singularity"
 	$ECHO "-g        \t use GPU instead of CPU"
-	$ECHO "-n [name] \t name of container instance (default: ${SERVER})"
+	$ECHO "-n [name] \t name of container instance, also used for hidden temporary dir (default: ${SERVER})"
 	$ECHO "-r [num]  \t number of retries when starting container (default: ${RETRIES})"
 	$ECHO "-v        \t (verbose) start: activate server debugging info; stop: keep server logs"
 	$ECHO "-w [time] \t maximum time to wait for server to start (default: ${WTIME} seconds)"
@@ -59,10 +59,16 @@ if [ "$OP" != start ] && [ "$OP" != stop ]; then
 	usage 1
 fi
 
+if [ "$RETRIES" -le 0 ]; then
+	RETRIES=1
+fi
+
+TOPDIR=$PWD
+TMPDIR=".${SERVER}"
 DOCKER="sudo docker"
 IMAGE=fastml/triton-torchgeo:20.09-py3-geometric
 MODELS=${CMSSW_BASE}/src/HeterogeneousCore/SonicTriton/data/models
-LOG=log_triton_server.log
+LOG="log_${SERVER}.log"
 LIB=lib
 STARTED_INDICATOR="Started GRPCInferenceService"
 EXTRA=""
@@ -100,8 +106,8 @@ start_singularity(){
 }
 
 stop_docker(){
-	# keep log
-	if [ -n "$VERBOSE" ]; then $DOCKER logs ${SERVER} >& ${LOG}; fi
+	# keep log (outside of tmp dir)
+	if [ -n "$VERBOSE" ]; then $DOCKER logs ${SERVER} >& "${TOPDIR}/${LOG}"; fi
 
 	$DOCKER stop ${SERVER}
 	$DOCKER rm ${SERVER}
@@ -110,9 +116,8 @@ stop_docker(){
 stop_singularity(){
 	singularity instance stop ${SERVER}
 
-	# cleanup
-	rm -rf ${LIB}
-	if [ -z "$VERBOSE" ]; then rm ${LOG}; fi
+	# move log out of tmp dir
+	if [ -n "$VERBOSE" ]; then mv "$LOG" "$TOPDIR"; fi
 }
 
 test_docker(){
@@ -160,6 +165,10 @@ else
 fi
 
 if [ "$OP" == start ]; then
+	# make sure everything happens in tmp dir
+	mkdir "$TMPDIR"
+	cd "$TMPDIR"
+
 	START_EXIT=""
 	for ((counter=0; counter < ${RETRIES}; counter++)); do
 		$START_FN
@@ -177,5 +186,17 @@ if [ "$OP" == start ]; then
 	fi
 	wait_server
 else
+	# check for tmp dir
+	if [ -d "$TMPDIR" ]; then
+		cd "$TMPDIR"
+	else
+		echo "Error: attempt to stop unknown container $SERVER"
+		exit 1
+	fi
+
 	$STOP_FN
+
+	# cleanup
+	cd "$TOPDIR"
+	rm -rf "$TMPDIR"
 fi
